### ISSUE TITLE
Make Kafka version

### ISSUE THREAD

**Issue by saharki** [saharki/icqueue#1]
Make Kafka version without breaking any API.

**Comment by saharki** [comment]
https://github.com/vectorizedio/redpanda can be use for testing.
RedPanda `docker-compose` for quick setup: https://vectorized.io/docs/quick-start-docker/#Bring-up-a-docker-compose-file

**Comment by saharki** [comment]
Running Kafka cluster with `docker-compose`: 
```bash
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-kafka/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```
[source](https://hub.docker.com/r/bitnami/kafka/)


I've edited the `docker-compose` attached above to contain UI:
```yml
version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest 
    ports:
      - "8080:8080" 
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - ALLOW_PLAINTEXT_LISTENER=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```
